name: Discord Notification

on: [push]

jobs:
  Notify:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        uses: Retr0-01/better-discord-notification@main
        with:
          webhook-url: ${{ secrets.CI_DISCORD_WEBHOOK }}
          embed-color: '16226832'
          footer-icon: 'https://cdn.discordapp.com/emojis/1100146654729998507.png'
